version: "3"
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
      MYSQL_USER: spring
      MYSQL_PASSWORD: secret
    networks:
      - network
networks:
  network: